version: '2'
services:
  cassandra:
    image: cassandra:2.2.5
  kong:
    image: mashape/kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    volumes:
      - ./kong/:/etc/kong/
    depends_on:
      - cassandra
    links:
      - cassandra:cassandra
    security_opt:
      - seccomp:unconfined
  dashboard:
    image: pgbi/kong-dashboard
    ports:
      - "8080:8080"
